# This is a config for E2B sandbox template.
# You can use template ID (798losodrfigltac696k) or template name (vibe-nextjs-mlhier) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-nextjs-mlhier") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-nextjs-mlhier") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-nextjs-mlhier')

team_id = "ec3d7e3f-a350-4323-aa97-26153184def9"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-nextjs-mlhier"
template_id = "798losodrfigltac696k"
